server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    mim-response-size: 1024 # Minimum "Content-Length" (in bytes) where compression will be performed.
  undertow:
    threads:
      worker: 64 # Generally this should be reasonably high, at least 10 per CPU core: https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners-2
      io: 4 # One IO thread per CPU core is a reasonable default: https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners-2

spring:
  datasource:
    url: jdbc:mysql://${mysql.url}/${mysql.database}?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${mysql.username}
    password: ${mysql.password}
    hikari: # Hikari is a connection pool manager
      auto-commit: false
      connection-timeout: 250 # 250ms, it's good to keep it small to not block the threads.
      max-lifetime: 600000 # Maximum time a connection can be kept open (10 min) - security.
      maximum-pool-size: 20 # At most 20 connections to the database. It's good to keep a low number as that's costly for the database to handle. https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
      minimum-idle: 10 # Can reduce the pool to a minimum of 10 connections if they are not being used.
      pool-name: master
  jpa:
    open-in-view: false # If true, Spring opens a new Hibernate Session at the beginning of the request.
    show-sql: true # Helps with troubleshooting but should be disabled in prod.
    hibernate:
      ddl-auto: none # Hibernate will not create or update the database schema
    properties:
      "[hibernate.dialect]": org.hibernate.dialect.MySQLDialect
      "[hibernate.generate_statistics]": false
      "[hibernate.connection.provider_disables_autocommit]": true
      # To maximize performance, we disable auto-commit and open-in-view.
      # https://vladmihalcea.com/why-you-should-always-use-hibernate-connection-provider_disables_autocommit-for-resource-local-jpa-transactions/
